@WebAPI_HostAddress = http://localhost:5270

POST {{WebAPI_HostAddress}}/api/auth/login/
Accept: application/json
Content-Type: application/json

{
  "userNameOrEmail": "deneme",
  "password": "şifre"
}

###
